# Generated by Django 6.0 on 2025-12-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
