# Generated by Django 6.0 on 2026-01-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_wish_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Чому це тобі потрібно?'),
        ),
    ]
