# Generated by Django 6.0 on 2026-01-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_wish_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на фото (URL)'),
        ),
    ]
